:logfile: log/sidekiq.log
:queues:
  - critical
  - high
  - default
  - mailers
  - low
:schedule:
  send_notification_digests:
    cron: "0 10 * * *" # runs once every day at 10am
    class: SendNotificationDigestsJob
  sync_talent_with_notion:
    cron: "0 20 * * *" # Runs once every day at 8pm
    class: SyncTalentWithNotionJob
  sync_on_chain_talent_supporters:
    cron: "0 * * * *" # Runs every hour
    class: TriggerTalentSupportersRefreshJob
    enabled: <%= ENV["ENABLE_THE_GRAPH_JOBS"] %>
  send_token_launch_reminder:
    cron: "0 10 * * *" # Runs once every day at 10am
    class: SendTokenLaunchReminderJob
  send_token_purchase_reminder:
    cron: "0 10 * * *" # Runs once every day at 10am
    class: SendTokenPurchaseReminderJob
